# Candidate Configuration - Fast Response
# This is a candidate configuration optimized for lower latency
metadata:
  name: "candidate_fast"
  description: "Candidate configuration optimized for lower latency"
  created_at: "2024-01-01T00:00:00Z"
  version: "1.2.0"
  tags: ["candidate", "fast"]

# Macro knobs - biased towards latency
macro_knobs:
  latency_guard: 0.8
  recall_bias: 0.3

# Derived parameters snapshot
derived_params:
  T: 1000
  Ncand_max: 700
  batch_size: 64
  ef: 96
  rerank_multiplier: 2

# Search pipeline configuration
retriever:
  type: hybrid
  alpha: 0.5
  vector_top_k: 150
  bm25_top_k: 150
  top_k: 50

reranker:
  type: cross_encoder
  model: cross-encoder/ms-marco-MiniLM-L-6-v2
  top_k: 50

# SLO targets
slo:
  p95_ms: 1200
  recall_at_10: 0.30


