# Candidate Configuration - High Recall
# This is a candidate configuration optimized for higher recall
metadata:
  name: "candidate_high_recall"
  description: "Candidate configuration optimized for higher recall"
  created_at: "2024-01-01T00:00:00Z"
  version: "1.1.0"
  tags: ["candidate", "high-recall"]

# Macro knobs - biased towards recall
macro_knobs:
  latency_guard: 0.3
  recall_bias: 0.8

# Derived parameters snapshot
derived_params:
  T: 500
  Ncand_max: 1200
  batch_size: 256
  ef: 224
  rerank_multiplier: 5

# Search pipeline configuration
retriever:
  type: hybrid
  alpha: 0.7
  vector_top_k: 300
  bm25_top_k: 300
  top_k: 50

reranker:
  type: cross_encoder
  model: cross-encoder/ms-marco-MiniLM-L-6-v2
  top_k: 50

# SLO targets
slo:
  p95_ms: 1200
  recall_at_10: 0.30


