/**
 * Generated types from backend API
 * DO NOT EDIT MANUALLY - generated by scripts/schema_check.mjs
 * Generated at: 2025-10-17T05:13:43.182Z
 */

export interface LabConfigResponse {
  ok: boolean;
  tabs: Array<{
    id: string;
    name: string;
    icon: string;
    description: string;
  }>;
  health: {
    ok: boolean;
    redis: { ok: boolean; message: string };
    qdrant: { ok: boolean; message: string };
    backend: { ok: boolean; message: string };
    reasons: string[];
  };
  quiet_mode: {
    enabled: boolean;
    required: boolean;
  };
  prewarm: {
    valid: boolean;
    prewarmed_at: number | null;
    required: boolean;
  };
  current_experiment: {
    running: boolean;
    type: string;
    experiment_id: string;
  } | null;
}

export interface LabStatusResponse {
  ok: boolean;
  running: boolean;
  experiment_id?: string;
  experiment_type?: string;
  phase?: string;
  current_round?: number;
  total_rounds?: number;
  current_window_progress?: number;
  current_noise?: number;
  windows?: Array<{
    timestamp: number;
    phase: string;
    p95_ms: number | null;
    qps: number;
    recall_at_10: number | null;
    samples: number;
    noise_index: number;
    valid: boolean;
  }>;
  deltas?: {
    deltaP95: number | null;
    deltaQPS: number | null;
    deltaRecall: number | null;
    a_count: number;
    b_count: number;
  };
  message?: string;
}

export interface LabMiniReportResponse {
  ok: boolean;
  delta_p95_pct: number;
  delta_qps_pct: number;
  error_rate_pct: number;
  message: string;
  generated_at: string | null;
}

export interface LabReportResponse {
  ok: boolean;
  report?: string;
  path?: string;
  error?: string;
  message: string;
}




































