retriever:
  type: vector
  collection: beir_scifact_full_ta
  top_k: 100                  # golden: candidate_k
reranker:
  type: cross_encoder
  model: cross-encoder/ms-marco-MiniLM-L-2-v2
  top_k: 50                   # golden: rerank_k
  batch_size: 32
  cache_size: 2000