retriever:
  type: hybrid
  alpha: 0.6
  vector_top_k: 100
  bm25_top_k: 100
  top_k: 100
  collection: beir_scifact_full_ta
reranker:
  type: cross_encoder
  model: cross-encoder/ms-marco-MiniLM-L-2-v2
  top_k: 30
  batch_size: 32
  cache_size: 2000