#!/bin/bash
# 诊断脚本：验证 50k preset 是否正确传递和使用

set -e

echo "=========================================="
echo "1. 检查前端 Payload（在浏览器 DevTools 中查看）"
echo "=========================================="
echo "启动一个实验后，在浏览器控制台查找："
echo "  [HANDLE_START] currentConfig: { dataset_name: 'fiqa_50k_v1', ... }"
echo "  [RUN PAYLOAD] { dataset_name: 'fiqa_50k_v1', qrels_name: 'fiqa_qrels_50k_v1', ... }"
echo ""
echo "在 Network 标签中查看 /api/experiment/run 请求，确认请求体包含："
echo "  dataset_name: 'fiqa_50k_v1'"
echo "  qrels_name: 'fiqa_qrels_50k_v1'"
echo ""

echo "=========================================="
echo "2. 检查后端日志和命令"
echo "=========================================="
echo "查看后端日志中的以下信息："
echo "  [RUN] Request dataset_name=fiqa_50k_v1, qrels_name=fiqa_qrels_50k_v1"
echo "  [ENQUEUE] Adding --dataset-name fiqa_50k_v1"
echo "  [ENQUEUE] Adding --qrels-name fiqa_qrels_50k_v1"
echo "  [CMD] ... --dataset-name fiqa_50k_v1 --qrels-name fiqa_qrels_50k_v1 ..."
echo ""

echo "=========================================="
echo "3. 检查 Qdrant 50k 集合"
echo "=========================================="
echo "执行以下命令检查 Qdrant 集合："
echo ""
echo "docker compose exec rag-api python3 << 'PYTHON_EOF'"
echo "import requests"
echo "import json"
echo ""
echo "# 获取所有集合"
echo "collections = requests.get('http://qdrant:6333/collections').json()"
echo "print('Collections:', json.dumps(collections, indent=2))"
echo ""
echo "# 检查 50k 集合"
echo "fiqa_50k = requests.get('http://qdrant:6333/collections/fiqa_50k_v1').json()"
echo "config = fiqa_50k.get('result', {}).get('config', {})"
echo "points_count = fiqa_50k.get('result', {}).get('points_count', 0)"
echo "vectors = config.get('params', {}).get('vectors', {})"
echo "dim = vectors.get('size', 0) if isinstance(vectors, dict) else 0"
echo ""
echo "print(f'\\nfiqa_50k_v1:')"
echo "print(f'  Points: {points_count}')"
echo "print(f'  Dimension: {dim}')"
echo "print(f'  Expected: ~50000 points, 384 dim (bge-small-v1.5)')"
echo "PYTHON_EOF"
echo ""

echo "=========================================="
echo "4. 测试运行一个 50k 实验"
echo "=========================================="
echo "运行以下命令启动一个测试实验："
echo ""
echo "JOB_ID=\$(curl -fsS -X POST http://localhost:8000/api/experiment/run \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"sample\":200,\"repeats\":1,\"fast_mode\":false,\"dataset_name\":\"fiqa_50k_v1\",\"qrels_name\":\"fiqa_qrels_50k_v1\"}' \\"
echo "  | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"job_id\"])')"
echo ""
echo "echo \"Job ID: \$JOB_ID\""
echo ""
echo "# 等待完成（最多 5 分钟）"
echo "for i in {1..150}; do"
echo "  STATUS=\$(curl -fsS http://localhost:8000/api/experiment/status/\$JOB_ID | python3 -c 'import sys,json;print(json.load(sys.stdin).get(\"state\",\"UNKNOWN\"))')"
echo "  echo \"[\$i] Status: \$STATUS\""
echo "  if [ \"\$STATUS\" = \"SUCCEEDED\" ] || [ \"\$STATUS\" = \"FAILED\" ]; then"
echo "    break"
echo "  fi"
echo "  sleep 2"
echo "done"
echo ""
echo "# 检查详情"
echo "curl -fsS http://localhost:8000/api/experiment/job/\$JOB_ID | python3 -m json.tool | grep -A 5 'params'"
echo ""

echo "=========================================="
echo "5. 验证详情页显示"
echo "=========================================="
echo "在浏览器中打开 Job 详情页面，确认："
echo "  Dataset: fiqa_50k_v1 (而不是 unknown)"
echo "  Qrels: 50k (或类似的显示)"
echo ""

echo "=========================================="
echo "6. 检查 Recall@10"
echo "=========================================="
echo "在 Job 详情页面的 Artifacts 部分查看："
echo "  - Recall at 10 图表"
echo "  - 如果值很低（如 0.039），可能需要："
echo "    1. 确认使用了正确的 collection (fiqa_50k_v1)"
echo "    2. 检查 top_k 参数（建议 >= 40）"
echo "    3. 确认 Qdrant 集合中有足够的数据点"
echo ""

echo "=========================================="
echo "修复总结"
echo "=========================================="
echo "✅ 前端："
echo "  - handleStart 中正确提取 dataset_name/qrels_name"
echo "  - startExperiment 中确保发送这些参数"
echo "  - 添加了 console.info 日志"
echo ""
echo "✅ 后端："
echo "  - RunRequest 支持 dataset_name/qrels_name"
echo "  - enqueue_run 构建命令时添加这些参数"
echo "  - JobMeta.params 保存这些参数"
echo "  - 添加了详细的日志"
echo ""
echo "✅ 详情页："
echo "  - 从多个来源读取 dataset_name/qrels_name"
echo "  - 支持从 cmd 命令中解析"
echo ""

