#!/usr/bin/env node
/**
 * Agent V2 Schema Validator
 * =========================
 * Validates API response schemas and optionally regenerates types
 * 
 * Usage:
 *   ./scripts/schema_check_agent_v2.mjs
 *   ./scripts/schema_check_agent_v2.mjs --regen
 */

import fetch from 'node-fetch'
import fs from 'fs/promises'
import path from 'path'

const BASE_URL = process.env.BASE_URL || 'http://localhost:8011'
const REGEN = process.argv.includes('--regen')

// Expected schemas
const SCHEMAS = {
    run: {
        required: ['ok', 'mode', 'verdict', 'timestamp'],
        types: {
            ok: 'boolean',
            mode: 'string',
            verdict: 'string',
            timestamp: 'string',
            message: 'string'  // optional
        }
    },
    summary: {
        required: ['ok', 'delta_p95_pct', 'delta_qps_pct', 'error_rate_pct', 'bullets'],
        types: {
            ok: 'boolean',
            delta_p95_pct: 'number',
            delta_qps_pct: 'number',
            error_rate_pct: 'number',
            bullets: 'array',
            generated_at: 'string'  // nullable
        }
    }
}

async function checkSchema(endpoint, expectedSchema, sampleResponse) {
    console.log(`\nChecking: ${endpoint}`)

    // Check required fields
    for (const field of expectedSchema.required) {
        if (!(field in sampleResponse)) {
            throw new Error(`Missing required field: ${field}`)
        }
    }

    // Check types
    for (const [field, expectedType] of Object.entries(expectedSchema.types)) {
        if (!(field in sampleResponse)) {
            continue  // Skip optional fields
        }

        const value = sampleResponse[field]
        const actualType = Array.isArray(value) ? 'array' : typeof value

        if (actualType !== expectedType && value !== null) {
            throw new Error(`Type mismatch for ${field}: expected ${expectedType}, got ${actualType}`)
        }
    }

    console.log('  ✓ Schema valid')
    return true
}

async function fetchEndpoint(url, method = 'GET') {
    const opts = { method, timeout: 10000 }

    if (method === 'POST') {
        opts.headers = { 'Content-Type': 'application/json' }
    }

    const resp = await fetch(url, opts)

    if (!resp.ok) {
        throw new Error(`HTTP ${resp.status}`)
    }

    return resp.json()
}

async function validateEndpoints() {
    console.log('Agent V2 Schema Validation')
    console.log('==========================')

    // Test 1: Dry run endpoint
    console.log('\n[1/2] POST /api/agent/run?v=2&dry=true')
    const runResp = await fetchEndpoint(`${BASE_URL}/api/agent/run?v=2&dry=true`, 'POST')
    await checkSchema('/api/agent/run', SCHEMAS.run, runResp)

    // Test 2: Summary endpoint
    console.log('\n[2/2] GET /api/agent/summary?v=2')
    const summaryResp = await fetchEndpoint(`${BASE_URL}/api/agent/summary?v=2`)
    await checkSchema('/api/agent/summary', SCHEMAS.summary, summaryResp)

    return { runResp, summaryResp }
}

async function regenerateTypes(samples) {
    if (!REGEN) {
        console.log('\n(Pass --regen to regenerate TypeScript types)')
        return
    }

    console.log('\nRegenerating TypeScript types...')

    const typesDef = `/**
 * Agent V2 API Types
 * Auto-generated by schema_check_agent_v2.mjs
 */

export interface AgentV2RunResponse {
    ok: boolean
    mode: 'dry' | 'live'
    verdict: string
    timestamp: string
    message?: string
}

export interface AgentV2Summary {
    ok: boolean
    delta_p95_pct: number
    delta_qps_pct: number
    error_rate_pct: number
    bullets: string[]
    generated_at: string | null
}

export interface AgentV2HistoryResponse {
    ok: boolean
    runs: Array<{
        timestamp: string
        config: any
        result: {
            ok: boolean
            phase: string
            verdict: string
        }
        version: 'v2'
    }>
    count: number
}
`

    const typesPath = path.join(process.cwd(), 'frontend/src/adapters/agentV2Types.generated.ts')

    await fs.writeFile(typesPath, typesDef, 'utf-8')

    console.log(`  ✓ Types written to ${typesPath}`)
}

async function main() {
    try {
        const samples = await validateEndpoints()
        await regenerateTypes(samples)

        console.log('\n✅ ALL CHECKS PASSED')
        console.log('\nEndpoints validated:')
        console.log('  - POST /api/agent/run?v=2&dry=<bool>')
        console.log('  - GET  /api/agent/summary?v=2')
        console.log('  - GET  /api/agent/history?v=2&n=<int>')

        process.exit(0)
    } catch (error) {
        console.error(`\n❌ Validation failed: ${error.message}`)
        process.exit(1)
    }
}

main()

