#!/usr/bin/env node
/**
 * Schema Check Script
 * Validates backend API responses and generates TypeScript types
 * 
 * Usage:
 *   BASE_URL=http://localhost:8011 ./scripts/schema_check.mjs
 *   or
 *   ./scripts/schema_check.mjs (defaults to http://localhost:8011)
 */

import { writeFile } from 'fs/promises'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const BASE_URL = process.env.BASE_URL || 'http://localhost:8011'

console.log(`🔍 Checking backend schemas at ${BASE_URL}...\n`)

// Fetch with error handling
async function fetchJson(url) {
  try {
    const response = await fetch(url)
    const text = await response.text()

    if (!response.ok) {
      console.warn(`⚠️  ${url} returned ${response.status}`)
      return { ok: false, status: response.status, text }
    }

    try {
      const json = JSON.parse(text)
      return { ok: true, data: json }
    } catch (e) {
      console.warn(`⚠️  ${url} returned non-JSON: ${text.substring(0, 100)}`)
      return { ok: false, error: 'Invalid JSON', text }
    }
  } catch (error) {
    console.error(`❌ Failed to fetch ${url}:`, error.message)
    return { ok: false, error: error.message }
  }
}

// Check endpoints
const endpoints = [
  { name: 'config', url: `${BASE_URL}/api/lab/config` },
  { name: 'status', url: `${BASE_URL}/api/lab/status` },
  { name: 'report_mini', url: `${BASE_URL}/api/lab/report?mini=1` }
]

const results = {}

for (const endpoint of endpoints) {
  console.log(`Checking ${endpoint.name}...`)
  const result = await fetchJson(endpoint.url)
  results[endpoint.name] = result

  if (result.ok) {
    console.log(`✅ ${endpoint.name}: OK`)
    console.log(`   Sample keys: ${Object.keys(result.data).slice(0, 5).join(', ')}`)
  } else {
    console.log(`⚠️  ${endpoint.name}: ${result.error || result.status || 'Failed'}`)
  }
  console.log()
}

// Generate TypeScript types
console.log('📝 Generating types.generated.ts...\n')

const typeDefinitions = `/**
 * Generated types from backend API
 * DO NOT EDIT MANUALLY - generated by scripts/schema_check.mjs
 * Generated at: ${new Date().toISOString()}
 */

export interface LabConfigResponse {
  ok: boolean;
  tabs: Array<{
    id: string;
    name: string;
    icon: string;
    description: string;
  }>;
  health: {
    ok: boolean;
    redis: { ok: boolean; message: string };
    qdrant: { ok: boolean; message: string };
    backend: { ok: boolean; message: string };
    reasons: string[];
  };
  quiet_mode: {
    enabled: boolean;
    required: boolean;
  };
  prewarm: {
    valid: boolean;
    prewarmed_at: number | null;
    required: boolean;
  };
  current_experiment: {
    running: boolean;
    type: string;
    experiment_id: string;
  } | null;
}

export interface LabStatusResponse {
  ok: boolean;
  running: boolean;
  experiment_id?: string;
  experiment_type?: string;
  phase?: string;
  current_round?: number;
  total_rounds?: number;
  current_window_progress?: number;
  current_noise?: number;
  windows?: Array<{
    timestamp: number;
    phase: string;
    p95_ms: number | null;
    qps: number;
    recall_at_10: number | null;
    samples: number;
    noise_index: number;
    valid: boolean;
  }>;
  deltas?: {
    deltaP95: number | null;
    deltaQPS: number | null;
    deltaRecall: number | null;
    a_count: number;
    b_count: number;
  };
  message?: string;
}

export interface LabMiniReportResponse {
  ok: boolean;
  delta_p95_pct: number;
  delta_qps_pct: number;
  error_rate_pct: number;
  message: string;
  generated_at: string | null;
}

export interface LabReportResponse {
  ok: boolean;
  report?: string;
  path?: string;
  error?: string;
  message: string;
}
`

// Write types file
const typesPath = join(__dirname, '../frontend/src/adapters/types.generated.ts')

try {
  await writeFile(typesPath, typeDefinitions, 'utf-8')
  console.log(`✅ Generated: ${typesPath}`)
} catch (error) {
  console.error(`❌ Failed to write types file:`, error.message)
  process.exit(1)
}

// Summary
console.log('\n' + '='.repeat(60))
console.log('SCHEMA CHECK SUMMARY')
console.log('='.repeat(60))

const allOk = Object.values(results).every(r => r.ok)

if (allOk) {
  console.log('✅ All endpoints validated successfully')
  console.log('✅ TypeScript types generated')
  console.log('\n✨ Schema check complete!')
  process.exit(0)
} else {
  const failed = Object.entries(results)
    .filter(([_, r]) => !r.ok)
    .map(([name, _]) => name)

  console.log(`⚠️  Some endpoints failed: ${failed.join(', ')}`)
  console.log('⚠️  Types generated with fallback definitions')
  console.log('\n⚠️  Schema check completed with warnings')
  process.exit(0) // Don't fail build, just warn
}


