#!/usr/bin/env python3
"""
Summarize extracted text using Ollama.
Outputs: summary.md
"""

import sys
import json
import subprocess
from pathlib import Path

# Configuration
OUTPUT_DIR = Path.home() / "searchforge" / "results" / "openclaw_demo"
EXTRACTED_TEXT = OUTPUT_DIR / "extracted.txt"
SUMMARY_OUTPUT = OUTPUT_DIR / "summary.md"
TARGET_CONFIG = OUTPUT_DIR / "target.json"
MODEL = "llama3:latest"

def read_extracted_text():
    """Read the extracted text file."""
    if not EXTRACTED_TEXT.exists():
        print(f"ERROR: Extracted text not found: {EXTRACTED_TEXT}", file=sys.stderr)
        sys.exit(1)
    
    with open(EXTRACTED_TEXT, "r", encoding="utf-8") as f:
        return f.read()

def get_target_url():
    """Get target URL from config."""
    if not TARGET_CONFIG.exists():
        return "Unknown"
    
    with open(TARGET_CONFIG) as f:
        config = json.load(f)
    return config.get("target_url", "Unknown")

def call_ollama(text_content):
    """Call Ollama to summarize the text."""
    # Truncate if too long (keep first 8000 chars to avoid token limits)
    text_preview = text_content[:8000]
    if len(text_content) > 8000:
        text_preview += "\n\n[Content truncated for summarization...]"
    
    prompt = f"""Summarize the following text about auto insurance. Provide:
1. 8-12 bullet points covering the main topics
2. A "Key Facts" section with important details
3. A "Quoted Snippets" section with 3-5 short, relevant quotes (each quote should be 1-2 sentences)
4. Keep the summary concise and factual.

Text to summarize:
{text_preview}

Format your response as markdown with clear sections."""
    
    print(f"Calling Ollama ({MODEL})...")
    
    try:
        # Use ollama run with timeout
        result = subprocess.run(
            ["ollama", "run", MODEL],
            input=prompt,
            text=True,
            capture_output=True,
            timeout=120,
            check=False
        )
        
        if result.returncode != 0:
            print(f"ERROR: Ollama failed with code {result.returncode}", file=sys.stderr)
            print(f"stderr: {result.stderr}", file=sys.stderr)
            sys.exit(1)
        
        return result.stdout.strip()
    
    except subprocess.TimeoutExpired:
        print("ERROR: Ollama call timed out", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: Failed to call Ollama: {e}", file=sys.stderr)
        sys.exit(1)

def format_summary(ollama_output, target_url):
    """Format the summary with source information."""
    summary = f"""# Summary

{ollama_output}

---

## Source

**URL**: {target_url}

*Generated by OpenClaw demo pipeline*
"""
    return summary

def main():
    print("Reading extracted text...")
    text_content = read_extracted_text()
    
    if len(text_content) < 100:
        print("ERROR: Extracted text is too short", file=sys.stderr)
        sys.exit(1)
    
    print(f"Text length: {len(text_content):,} characters")
    
    # Get summary from Ollama
    ollama_output = call_ollama(text_content)
    
    # Get target URL
    target_url = get_target_url()
    
    # Format and save
    summary = format_summary(ollama_output, target_url)
    
    with open(SUMMARY_OUTPUT, "w", encoding="utf-8") as f:
        f.write(summary)
    
    print(f"Summary saved: {SUMMARY_OUTPUT}")
    print(f"Summary length: {len(summary):,} characters")

if __name__ == "__main__":
    main()
